### ISSUE TITLE
Is this work really based on self-supervised learning?

### ISSUE THREAD

**Issue by WXR1998** [cruiseresearchgroup/TSCP2#3]
I can't find a data augmentation module in the code.
In the 'train_prep' function, the code directly uses the label read from input files

**Comment by shohreh-deldari1** [comment]
Hi , 
Thanks for your interest in our work.
The labels will be used for the final evaluation only. 
We didn't use an augmentation technique. The model works on the raw data of two adjacent windows.

Please let me know if there is any other questions.
Kind regards
