### ISSUE TITLE
Can TSCP2 solve multivariate time series problem?

### ISSUE THREAD

**Issue by hhhercules** [cruiseresearchgroup/TSCP2#4]
Thanks for open source. I'm very interested in this work！
I noticed that when loading the data, the multivariate time series was converted to a single-dimensional time series. 
`ts = np.sqrt(np.power(x[:, 0], 2) + np.power(x[:, 1], 2) + np.power(x[:, 2], 2))`
 Is it because the model can't handle multivariate time series? If not, what should I do with multivariate time series using this method?

**Comment by nttung1110** [comment]
Thanks for the great work. I think you might forget to upload the tcn module inside ```TSCP2.py``` file. Can you check it again since I can't find it elsewhere inside your repo? Thanks for your help.

**Comment by shohreh-deldari1** [comment]
Thank you for your question. In short, yes, you can still apply this work to any multivariate time series. However, I suggest changing the input dimension regarding the input data appropriately. Basically, you can change the encoder according to your input data or task and still stick to the idea of contrastive learning.
